# Generated by Django 5.1.4 on 2025-01-06 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchit_app", "0002_alter_signup_email_alter_signup_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Signup",
        ),
    ]
