# Generated by Django 4.2.26 on 2026-02-10 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watchit_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='pending_participants',
            field=models.ManyToManyField(blank=True, related_name='pending_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
