# Generated by Django 4.2.26 on 2026-02-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit_app', '0005_watchparty_pending_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='movie_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watchparty',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
