# Generated by Django 4.2.26 on 2026-02-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit_app', '0006_watchparty_movie_title_watchparty_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
