# Generated by Django 4.2.28 on 2026-03-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit_app', '0007_watchparty_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchparty',
            name='movie_type',
            field=models.CharField(default='movie', max_length=20),
        ),
        migrations.AddField(
            model_name='watchparty',
            name='total_seasons',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watchparty',
            name='current_source',
            field=models.CharField(default='embedmaster', max_length=50),
        ),
    ]
