# Generated by Django 4.2.28 on 2026-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit_app', '0008_watchparty_movie_type_watchparty_total_seasons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=50)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
                ('episode_name', models.CharField(max_length=255)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vote_count', models.IntegerField()),
                ('air_date', models.DateField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('show_id', 'season_number', 'episode_number')},
            },
        ),
    ]
