# Generated by Django 4.2.28 on 2026-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchit_app', '0009_episoderating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('tmdb_id', models.CharField(max_length=50)),
                ('show_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
