# Generated by Django 5.1.5 on 2025-01-20 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="imdb_id",
            field=models.CharField(
                default="default_imdb_id", max_length=50, unique=True
            ),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="movie_title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="movie_year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="poster",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="added_on",
        ),
        migrations.RemoveField(
            model_name="watchlist",
            name="movie",
        ),
    ]
