# Generated by Django 5.1.5 on 2025-01-20 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_app",
            "0002_alter_watchlist_unique_together_watchlist_imdb_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watchlist",
            new_name="Watchlists",
        ),
    ]
