# Generated by Django 5.1.5 on 2025-01-20 16:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0003_rename_watchlist_watchlists"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Watchlists",
            new_name="Watchlist",
        ),
    ]
