# Generated by Django 5.1.5 on 2025-01-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_app", "0004_rename_watchlists_watchlist"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="watchlist",
            options={"verbose_name": "Watchlist", "verbose_name_plural": "Watchlists"},
        ),
    ]
