# Generated by Django 5.1.4 on 2025-01-28 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_alter_watchlist_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='imdb_id',
            field=models.CharField(default='default_imdb_id', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'imdb_id')},
        ),
    ]
