# Generated by Django 4.2.26 on 2025-12-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_room_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='movie_type',
            field=models.CharField(default='movie', max_length=20),
        ),
    ]
