# Generated by Django 4.2.26 on 2025-12-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0010_room_movie_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
