# Generated by Django 4.2.26 on 2025-12-21 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0011_remove_room_host_delete_chatmessage_delete_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added_on'], 'verbose_name': 'Watchlist', 'verbose_name_plural': 'Watchlists'},
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='imdb_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='poster',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
