# Generated by Django 4.2.26 on 2025-12-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0013_create_default_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
